on: push
name: deploy
jobs: 
  build:
  name: deploy to repository
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.Prueba }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}